# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

# If we have a branch with an open PR do not build the branch.  This removes
# the duplicate build for any updates on a PR, which consume a lot of scarce
# AppVeyor build slots.
skip_branch_with_pr: true

image:
  - Visual Studio 2017

environment:
  matrix:
    - PROVIDER: vcpkg
      CONFIG: Debug
      APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
  - c:\projects\vcpkg\installed

install:
  - choco install -y ninja
  - git submodule update --init
  - powershell -exec bypass ci\appveyor\install-windows.ps1

build_script:
  - call "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - powershell -exec bypass ci\appveyor\build-windows.ps1

test_script:
  - ps: cd build-output
  - ctest --output-on-failure -C "%CONFIG%"
