disabled: true
filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: google-cloud-cpp
  owner: googleapis
  pullRequest:
    branch: ^master$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: clang-tidy
substitutions:
  _BUILD_NAME: clang-tidy
  _DISTRO: fedora
